module.exports = {
  someSidebar: {
    "Welcome": ["introduction"],
    "Getting started": [ "getting_started_deployments", 
                         "getting_started_usage"],
    "Installation": ["installation_system-deployment"],
    "Compute Environments": ["compute_overview", 
                             "compute_aws-batch",
                             "compute_azure-batch",
                             "compute_google-cloud",
                             "compute_altair-pbs-pro",
                             "compute_grid-engine",
                             "compute_lsf",
                             "compute_slurm",
                             "compute_eks",
                             "compute_gke",
                             "compute_k8s"],
    "Launching Pipelines": ["launch_overview", 
                            "launch_advanced",
                            "launch_notifications",
                            "launch_relaunch"],
    "Monitoring Pipelines": ["monitoring_overview",
                             "monitoring_execution",
                             "monitoring_summary",
                             "monitoring_processes",
                             "monitoring_aggregate_stats",
                             "monitoring_tasks",
                             "monitoring_sharing"],
    "Git Integration": [ "git-overview", 
                         "git-public", 
                         "git-private"],
    "Automation": ["pipeline-actions"],
    "API": ["api_overview",  
            "api_endpoints",
            "api_openapi"],
  },
};
