module.exports = {
  someSidebar: {
    "Welcome": ["introduction"],
    "Getting started": [ "getting_started_deployments", "getting_started_usage"],
    "Installation": ["installation_system-deployment"],
    "Compute Environments": ["compute_overview", 
                             "compute_aws-batch",
                             "compute_azure-batch",
                             "compute_google-cloud",
                             "compute_altair-pbs-pro",
                             "compute_grid-engine",
                             "compute_lsf",
                             "compute_slurm",
                             "compute_eks",
                             "compute_gke",
                             "compute_k8s"],
    "Launching Pipelines": ["launch_overview", "launch_notifications", "launch_advanced", "launch_relaunch"],
    "Monitoring Pipelines": [],
    "Git Integration": [ "git-overview", "git-public", "git-private"],
    "Automation": [],
    "API": ["api_overview", "api_openapi", "api_endpoints"],
  },
};
